### ISSUE TITLE
Display the Neural Network?

### ISSUE THREAD

**Issue by Bobingstern** [flo-wolf/UnitySharpNEAT#3]
Is it possible to show the neural network on the screen? Also, does the neural network change in shape? I assume It does but some videos I've seen had a static neural net so I just want to be sure.

**Comment by flo-wolf** [comment]
To your first question, at the moment its not, but its a cool feature I had in mind for quite some time now.

Regarding whether the neural netoworks change in shape, they do. Its what the NEAT algorithm is responsible for: The neural nets start small (and dumb) and grow over generations through mutations and selection. You can have a look at the generated neural nets by opening the .pop.xml (population, aka all brains) or the .champ.xml (best brain) in 'AppData/LocalLow/DefaultCompany/ExperimentName.champ.xml' (DefaultCompany might differ inyour case) after you have generated the saves by clicking on the 'Stop' button. These are normally used to generate the population again after closing and reponening the simulation. Inside of the files the brain structure grows. Try evolving many generations, then saving and then look into the file again, the brains will have grown in most cases - except of course there is already an optimal solution possible, given the inputs and outputs have a suitable weightcombination already, that doesnt need any extra nodes to be created. If that's the case, you can easily make the task more complicated.

**Comment by Bobingstern** [comment]
Ok, Thanks for your response!
